export enum  AllCoinsActionTypes{
    FETCH_ALL_COINS = 'FETCH_ALL_COINS',
    FETCHING = 'FETCHING',
    FETCH_COINS_ERROR = 'FETCH_COINS_ERROR',
    FETCH_SINGLE_COIN = 'FETCH_SINGLE_COIN',
    DEFAULT_SINGLE_COIN = 'DEFAULT_SINGLE_COIN',
}